### PR TITLE
Fix + allow elywing phar

### PR DESCRIPTION
**Pull request by ondraczsk**
fixed

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Best fix: *.phar

**Comment by ondraczsk** [comment]
i copy this from https://github.com/H4PM/Elywing/commit/2d5aae780900c2b7c974ac4a50cce466ab84f8a4

**Comment by thebigsmileXD** [comment]
Yes, but *.phar would recognize any phar, that means if a user accidently names it pmmp.phar etc.

**Comment by ondraczsk** [comment]
But! There is a Elywing*.phar
This is useful if do you using builds like Elywing_2017-10-1.phar
i thing :D

**Comment by thebigsmileXD** [comment]
True

**Pull request merged**
