### PR TITLE
Added new items to Creative inv

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by Driesboy** [comment]
working!

**Comment by erkam2002** [comment]
I know but not finished wait :)

**Comment by erkam2002** [comment]
I test it

**Comment by Driesboy** [comment]
dargon?

**Comment by erkam2002** [comment]
?

**Comment by Driesboy** [comment]
https://github.com/H4PM/Elywing/pull/168/commits/4e8f58f4b1d2dace3674cd2a73ad837ffcba47bc

**Comment by erkam2002** [comment]
Why not?

**Comment by Driesboy** [comment]
dargon? is it not dragon?

**Comment by erkam2002** [comment]
That is fragonbreath ...
screenshot 16

**Comment by erkam2002** [comment]
FINISHED

**Comment by erkam2002** [comment]
Now it fixed

**Comment by erkam2002** [comment]
Please accept all pull request code is tested and work succesfully if you want can you test it on ->
5.135.250.171 Port 5050

**Comment by erkam2002** [comment]
Yeah

**Pull request merged**
