### PR TITLE
Update 1.0

### PR DESCRIPTION
**Pull request by Infernus102**
putItemHelper() => nbtSerialize() and getItemHelper() => nbtDeserialize()

### CODE REVIEW

**Comment by SuperMaXAleX** [comment]
What's changed exactly ?

**Comment by Infernus102** [comment]
read description

**Comment by SuperMaXAleX** [comment]
Ya but I don't understand what this code affect exactly.

**Comment by Infernus102** [comment]
it's a 1.0 update, just like other things were changed

**Comment by Infernus102** [comment]
https://github.com/H4PM/Elywing/blob/d8f0e15d7760b28e98c33f3f48090832ec4e0b7d/src/pocketmine/level/format/region/McRegion.php#L54

**Comment by Infernus102** [comment]
https://github.com/H4PM/Elywing/blob/d8f0e15d7760b28e98c33f3f48090832ec4e0b7d/src/pocketmine/level/format/region/Anvil.php#L42

**Comment by Infernus102** [comment]
https://github.com/H4PM/Elywing/blob/d8f0e15d7760b28e98c33f3f48090832ec4e0b7d/src/pocketmine/level/format/region/PMAnvil.php#L46

**Comment by Infernus102** [comment]
https://github.com/H4PM/Elywing/blob/337bd17f3400ef14718d668b87322318976b5611/src/pocketmine/item/Item.php#L1012

**Comment by SuperMaXAleX** [comment]
Tested and approved?

**Comment by Infernus102** [comment]
yes

**Comment by isoz** [comment]
"What's changed"
"stuff changed its a 1.0 update!!1 like the others"

ahaha gotta love that nobody knows what they're talking about

**Pull request merged**
