### PR TITLE
Couple of things

### PR DESCRIPTION
**Pull request by Pogogo007**
A couple of things will be added to this pr soon rn its only to fix the item pickup bug

### CODE REVIEW

**Comment by Pogogo007** [comment]
Dont merge this rn im adding Enderpearl item

**Comment by Pogogo007** [comment]
Merge ready

**Comment by Pogogo007** [comment]
Do not merge.

**Comment by Pogogo007** [comment]
Fuck enderpearls

**Comment by Pogogo007** [comment]
Merge back ready xd

**Comment by TheAppleGamer** [comment]
Unable to hear items being picked up

**Comment by Pogogo007** [comment]
Thats a problem with sound thingies ill check soon

**Comment by Muqsit** [comment]
Woah, thanks!

**Pull request merged**
