### PR TITLE
Make it easier to contribute

### PR DESCRIPTION
**Pull request by mcpesrccode**
Merge this and you will be banned from my server at 127.0.0.1! This can waste the precious 5% of the disk space of the 1KB floppy disk I'm hosting my banned-players.txt with (I modified Elywing to save the banned player lists in floppy disks for eco-friendliness! So many floppy disks wasted in the landfill! We need greener servers!), so it is definitely worth the cost destroying my server!

- Obsoletes #280
  - Obviously, #280 was closed due to problems with branching. The commit has since been cherry-picked!
  - Elywing is a community project that allows everyone to contribute, so #280 was closed obviously to let another pull request obsolete it!
- GPG-verified! Not a product of cherry-picking! Confirmed origin from @mcpesrccode, owner of the best server in his computer at 127.0.0.1!
  - You should GPG-verify your commits too! I sometimes wonder if the commits were actually created by you!

It is so important to let everyone know how to contribute correctly!

I will actively update this pull request to keep it clean against master! Have fun rebasing!

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
👎

**Comment by mcpesrccode** [comment]
Updated branch in the hope that you would exhibit your understanding of the existence of "Protect branch" and its value instead of showing off your rebasing and cherry-picking skills every day.

**Comment by thebigsmileXD** [comment]
@mcpesrccode was that a try to insult me? wtf

**Comment by mcpesrccode** [comment]
@thebigsmileXD of course not! Extremely am I surprised by your genius talent having managed to comprehend and utilize the advanced concepts of Git rebase that few have accomplished. In this field doubtlessly are you the top thousandth, if not the millionth, among the intelligent beings on Earth to be gifted to rescue Earth from resource shortage through the anabolism of binding various commits into complex but single commits. Nevertheless illiterate is most of the world with your puzzling distinctive capability of utilizing Git features, your great potential can be better known through displaying your usage of protected branches.

**Comment by thebigsmileXD** [comment]
> instead of showing off your rebasing and cherry-picking skills every day.

What i did.

**Comment by Muqsit** [comment]
Please stop acting immature. This PR is useless, just another person trying to seek attention by using one of the most overused sentences.
Never heard for someone complaining at all, great skills you got there mate. Originality 10/10.

**Comment by mcpesrccode** [comment]
What sentence did I overuse o.O

**Comment by thebigsmileXD** [comment]
@Muqsit oh you wouldn't  believe how many complain..

**Pull request closed without merging**
