### PR TITLE
Fixed Normal.php

### PR DESCRIPTION
**Pull request by ondraczsk**
fix rainfall to tempature

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Others, please approve

**Comment by Infernus102** [comment]
everyone's inactive

**Comment by ondraczsk** [comment]
:D

**Comment by Infernus102** [comment]
haahahahahahaha

**Comment by AppleDevelops** [comment]
I'm updating Elywing level format to match https://github.com/TesseractTeam/Tesseract/commit/8083478ade1042057a0e6af53b024bed2785b6ae I've already started and it's stabler. This PR might not be needed.

**Pull request closed without merging**
