### PR TITLE
All comits @erkam2002 in one PR.

### PR DESCRIPTION
**Pull request by NycuRO**
That's more easy. @erkam2002

### CODE REVIEW

**Comment by erkam2002** [comment]
How?

**Comment by erkam2002** [comment]
Come on this server UniFreesNet.de 5050 its a test server

**Comment by erkam2002** [comment]
accept this anyone? or..

**Comment by SuperMaXAleX** [comment]
We are waiting before to accept it.

**Comment by erkam2002** [comment]
Waiting for?

**Comment by erkam2002** [comment]
@SuperMaXAleX if you want to test come on UniFreesNet.de Port 5050

**Comment by Driesboy** [comment]
my server also have the newest version with this addons but ITS FULL :(
100 players is the max for my internet :(

**Comment by erkam2002** [comment]
Addons?

**Comment by Driesboy** [comment]
blocks etc this is added to the original version 🥇

**Comment by erkam2002** [comment]
My version ?

**Comment by NycuRO** [comment]
@Driesboy Ip? port?

**Comment by Driesboy** [comment]
gamecraftpe.tk port 19132
but TELENET is working on my internet!! and now i dont have internet!

**Pull request merged**
