### PR TITLE
Fix beacon and sea lanterns "not glowing" after relogging

### PR DESCRIPTION
**Pull request by Xelcronia**
Tested and works!

### CODE REVIEW

**Comment by thebigsmileXD** [comment]
Didnt knew you have things like SolidLight. ClearSky had an interface LightSource. Should maybe changed in Elywing too, so its just SeaLantern extends Solid implements LightSource

**Comment by Xelcronia** [comment]
I looked into https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/block/Glowstone.php

**Comment by thebigsmileXD** [comment]
Yea.. genisys way of light calculation

**Comment by Xelcronia** [comment]
Since Elywing's block codes are from Genisys, I did the same for Lantern and Beacon

**Comment by thebigsmileXD** [comment]
Yea correct.

**Pull request merged**
