### PR TITLE
Actually fix ender pearl.

### PR DESCRIPTION
**Pull request by KennFatt**

### CODE REVIEW

**Comment by KennFatt** [comment]
please someone test it twice, i had an issue when Player jump then throw the ender pearl.

```
Notice: Undefined index: pocketmine\entity\EnderPearl in phar:///Kennan/dev/mcpe/elywing/PocketMine-MP.phar/src/pocketmine/entity/Entity.php on line 644
```

**Comment by KennFatt** [comment]
Done! check and make review please.

**Comment by daniktheboss** [comment]
Your good your good thanks. They did nothing to the ender pearl last update (no hate)

**Comment by AppleDevelops** [comment]
It could have been something as simple as this https://github.com/H4PM/Elywing/commit/324b01adc629b2b38bcc01e09ce5084b05a1b6f4

**Comment by KennFatt** [comment]
@AppleDevelops fixed already?

**Pull request closed without merging**
