### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by archie426**
PocketMine Forums will not support this.

### CODE REVIEW

**Comment by caspervanneck** [comment]
close this plz

**Comment by archie426** [comment]
Why?????

**Comment by TDMidkwhatisxd** [comment]
Close this and ban the stupid kid!

**Comment by archie426** [comment]
THE FORUMS DOESNT SUPPORT ELYWING

**Comment by caspervanneck** [comment]
@archie426  its for plugins and this is a fork not a spoon

**Comment by archie426** [comment]
Yeah, a fork that copies and pastes code and never pushes. Forks are fan made branches, technically, helping the original project. A spoon is a 3rd party build. Which is what this is

**Comment by TDMidkwhatisxd** [comment]
I saw in pocketmime forums! They got angry that Elywing got popular! 
I just use what is stable! I have no errors until now (just plugins errors o-o ), so im happy with that!

**Comment by archie426** [comment]
Yes, because all you/owners have done is copied code and called it 'stable' . And then directed all support to Poketmine forums

**Comment by daniktheboss** [comment]
@tdmidkwhatisxd Please shut up! You are pissing me off and others as well!

**Comment by TDMidkwhatisxd** [comment]
Noobs :/

**Comment by archie426** [comment]
@TDMidkwhatisxd Yeah, you have got a lot of room to call people 'Noobs'

**Comment by TDMidkwhatisxd** [comment]
For me you are some .... Idk, just some noobs that have time to act smart!  # GetRekt

**Comment by archie426** [comment]
Errrr, why are you liking your own posts...... that is just sad......

**Comment by TDMidkwhatisxd** [comment]
All come to Elywing the most stable fork out here! I use it, that makes a difference! Ik you all jelly noobs tryed to ddos my server becouse is Top 1 ! # GetRekt

**Comment by TDMidkwhatisxd** [comment]
Just to say! Elywing is not my Stable Fork! 
I have no acces, i just dont like bullyes ! Leave it alone and go on! If i had acces i would ban u !

Im just a server owner, not a dev!

**Comment by daniktheboss** [comment]
Lmao! Are you the owner of lifeboat?

**Comment by TDMidkwhatisxd** [comment]
https://minecraftpocket-servers.com

This is why i hate noobs 😒

**Comment by SuperMaXAleX** [comment]
Stoop...

**Comment by TDMidkwhatisxd** [comment]
The lock this, i hate them posting what they wanna!

**Comment by daniktheboss** [comment]
Are u the noob? You don't even know how to write a simple plugin!! I know
more then u!

**Comment by TDMidkwhatisxd** [comment]
Please read up!
Even monkeys can read! Why u cant? Maybe u a flea?

**Comment by archie426** [comment]
Ok ok. STOP OFFENDING EACH OTHER. The author has already decided that this is going to be a plugin. Please lock and limit.

**Comment by daniktheboss** [comment]
Plugin? What do you mean by make a plugin??

**Comment by daniktheboss** [comment]
Um I'm a human... maybe ur a flea

**Comment by SuperMaXAleX** [comment]
Elywing is going to add more possibility to Genisys / PocketMine etc
- New entities
- New packets
- New events
etc etc
But
all this things on a plugin.

**Comment by SuperMaXAleX** [comment]
@archie426 He'll lock, don't worry

**Pull request merged**
