### PR TITLE
Update start.cmd for Elywing

### PR DESCRIPTION
**Pull request by caspervanneck**

### CODE REVIEW

**Comment by caspervanneck** [comment]
its tested and it works great

**Comment by TDMidkwhatisxd** [comment]
Should be able to run PocketMine-MP.phar too ! Becouse all forks are based on official Pocketmine!

**Comment by caspervanneck** [comment]
@TDMidkwhatisxd it works now with PocketMine-MP.phar

**Comment by Adam1609** [comment]
But, change font to Consolas please....

**Comment by caspervanneck** [comment]
@Adam1609 its Consolas take a better look

**Pull request merged**
