### PR TITLE
Duplication fix

### PR DESCRIPTION
**Pull request by TDMidkwhatisxd**
If players wanna craft they should go to setting/video/advanced/ and change pocket to classic!
Items wont drop anymore if stuck in floating inventory!

I did a mystake i will try to edit!

### CODE REVIEW

**Comment by SuperMaXAleX** [comment]
Tested ?

**Comment by TDMidkwhatisxd** [comment]
Ya! Players may experience item loss, if they stuck on floating!
Is sad, that we cant private chat in github to give u server ip!

But no errors in console!

**Comment by TDMidkwhatisxd** [comment]
Alex, a ideea! Why no add a swich? Maybe some players wanna the duplication glich! I mean, they dont wanna players to lose stuff wen a item is stuck on floating inventory!

**Comment by SuperMaXAleX** [comment]
mhhh, nah

**Comment by TDMidkwhatisxd** [comment]
Then ok!

**Review by raven0034 — COMMENTED** [review]
good job

**Comment by TDMidkwhatisxd** [comment]
I use it on my server! No errors! 
Is just that if u force craft, or u use mods to trigger gliches, items may be lost in floating inventory !

But dupe glich fixed!

**Comment by Infernus102** [comment]
True @TDMidkwhatisxd , i use it too

**Comment by TDMidkwhatisxd** [comment]
Oh! Ok! Sorry!

**Pull request closed without merging**
