### PR TITLE
fix from genisys

### PR DESCRIPTION
**Pull request by TDMidkwhatisxd**
Drop item event fix from Genisys
Now we can cancel it :)!

### CODE REVIEW

**Comment by TDMidkwhatisxd** [comment]
My bad! It really gliched on my web editor! :0

**Comment by TDMidkwhatisxd** [comment]
why it glich ;-;

**Comment by TDMidkwhatisxd** [comment]
@Muqsit  can u do it? It seems that I glich even on my pc -.-

**Comment by Muqsit** [comment]
Use tabs instead of space bars.

**Comment by TDMidkwhatisxd** [comment]
it makes my pc lag :( file too big xd !

**Pull request merged**
