### PR TITLE
Make it easier to contribute

### PR DESCRIPTION
**Pull request by mcpesrccode**
PMMP has `3**5` stargazers while Elywing only has `3**4-3**2` stargazers. This is terrible! Elywing is awesome!

### CODE REVIEW

**Comment by mcpesrccode** [comment]
I hereby clarify that this pull request's code is ALL RIGHTS RESERVED. **Merge it and you will be sued**; this isn't like the code you are used to copy; this is ALL RIGHTS RESERVED!

**Comment by isoz** [comment]
ALL RIGHTS RESERVED? Is that some new kind of license? sue me bitch

**Comment by Aericio** [comment]
@mcpesrccode i can no join svr plz help!!!

**Comment by thebigsmileXD** [comment]
@mcpesrccode > I hereby clarify that this pull request's code is ALL RIGHTS RESERVED. Merge it and you will be sued; I will report to the admins on my servers and ask them to ban you from my server at 127.0.0.1 (join it, it has a lot of air blocks and very fun crashes! It uses Elywing!). This isn't like the code you are used to copy; this is ALL RIGHTS RESERVED!

Kewl
Reserve rights without perms? Hell yea! Thats fun!
Wohoo, ban from local server? Wow, i am impressed of your skills. Have fun banning us.

**Comment by Aericio** [comment]
@thebigsmileXD he wil ban u from svr!!! he own minecfrat!!! dont mess with him! he will ban u!

**Pull request closed without merging**
