### PR TITLE
Update names + Fixed InstallerLang.php + Added Czech

### PR DESCRIPTION
**Pull request by ondraczsk**
fixed genisys> elywing

### CODE REVIEW

**Comment by Driesboy** [comment]
other languages???

**Comment by Takesikaityo** [comment]
I can speak Japanese.
Can I help you?

**Comment by Driesboy** [comment]
i think he only need to change names its the same in every languages xD

**Comment by ondraczsk** [comment]
@Driesboy im going to change names now

**Comment by Driesboy** [comment]
k

**Comment by ondraczsk** [comment]
@Driesboy Pls help i change chs.ini but i dont want create new pull request,
how to add another file to this pull? sry for my english

**Comment by SuperMaXAleX** [comment]
I'll merge it when every languages is going to be modified ;)

**Comment by Driesboy** [comment]
edit it in patch-1 @ondraczsk

**Comment by ondraczsk** [comment]
ok

**Comment by ondraczsk** [comment]
@Driesboy @SuperMaXAleX @Takesikaityo
 Finished.

**Comment by ondraczsk** [comment]
hm?

**Comment by thebigsmileXD** [comment]
Not compatible with latest code. Please create a new PR, this one is way too messy to merge.

**Pull request closed without merging**
