### PR TITLE
Crafting Bug Fix #250

### LINKED ISSUE #247: Can't craft item from crafting table!
When craft item at crafting table, It cancelled.
Reference under movie
* Link(DropBox) : https://www.dropbox.com/s/nixuon1rnxb8ngn/mobizen_20170101_101201.mp4?dl=0

### LINKED ISSUE #250: Craft's don't work
When player join in crafting table and crafting anything craft don't work.

### PR DESCRIPTION
**Pull request by Infernus102**
Crafting bug fix #250 #247 #27 #154 #160

### CODE REVIEW

**Comment by SuperMaXAleX** [comment]
Tested and working ?

**Comment by Infernus102** [comment]
Working for me

**Comment by Infernus102** [comment]
Fixed and working i hope

**Comment by Infernus102** [comment]
@SuperMaXAleX What are you waiting for? merge this or test it your self it works

**Comment by SuperMaXAleX** [comment]
uh

**Comment by SuperMaXAleX** [comment]
I wanted to merge it. ;-;

**Comment by Infernus102** [comment]
It's a buggy code, thats what there is to it.

**Comment by SuperMaXAleX** [comment]
ah

**Comment by Infernus102** [comment]
ugh this is not getting fixed!!

**Pull request closed without merging**
